"""Check if program reports are being saved"""
import asyncio
from sqlalchemy import select, func
from app.database import engine
from app.models import Report

async def check_reports():
    async with engine.begin() as conn:
        from sqlalchemy.ext.asyncio import AsyncSession
        
        async with AsyncSession(conn, expire_on_commit=False) as session:
            # Get all reports
            stmt = select(Report).order_by(Report.generated_at.desc()).limit(10)
            result = await session.execute(stmt)
            reports = result.scalars().all()
            
            print(f"\n=== Recent Reports (Last 10) ===")
            print(f"Total reports found: {len(reports)}\n")
            
            for i, report in enumerate(reports, 1):
                print(f"{i}. Report ID: {report.id}")
                print(f"   Title: {report.title}")
                print(f"   Type: {report.report_type}")
                print(f"   Status: {report.status}")
                print(f"   Generated At: {report.generated_at}")
                print(f"   Barangay ID: {report.barangay_id}")
                print(f"   Generated By: {report.generated_by}")
                print()

if __name__ == "__main__":
    asyncio.run(check_reports())
